[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
boat_final = "4Gu2ktcq8wjcwA2MdxsKLdrffxkDm1MWY6gK44SymRwP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/ubuntu/data5500_mycode/hw10/boat_final/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
