/**
 * Convert snarkjs verification_key.json → Rust Groth16Verifyingkey const
 * (compatible with groth16-solana 0.2.x / Light Protocol byte layout).
 *
 * Usage: npx tsx scripts/export_vk_rust.ts build/verification_key.json \
 *          ../../programs/boat_final/src/verifying_key.rs
 */
import fs from "fs";
import path from "path";

function bigintToBe32(s: string): number[] {
  let n = BigInt(s);
  const out = new Array<number>(32).fill(0);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(n & 0xffn);
    n >>= 8n;
  }
  return out;
}

function processG2Pair(pair: string[]): number[] {
  // LE pad each, concat, reverse full 64, return 64 bytes
  const toLe32 = (s: string) => {
    let n = BigInt(s);
    const le: number[] = [];
    for (let i = 0; i < 32; i++) {
      le.push(Number(n & 0xffn));
      n >>= 8n;
    }
    return le;
  };
  const concat = [...toLe32(pair[0]), ...toLe32(pair[1])];
  concat.reverse();
  return concat;
}

function bytesLit(bytes: number[]): string {
  return bytes.map((b) => `${b}u8`).join(", ");
}

function main() {
  const src = process.argv[2] ?? "build/verification_key.json";
  const dest =
    process.argv[3] ??
    path.join("..", "..", "programs", "boat_final", "src", "verifying_key.rs");
  const vk = JSON.parse(fs.readFileSync(src, "utf8"));

  const alpha = [
    ...bigintToBe32(vk.vk_alpha_1[0]),
    ...bigintToBe32(vk.vk_alpha_1[1]),
  ];
  // snarkjs G2: drop trailing z ["1","0"]; each remaining pair is [c0,c1]
  const g2 = (field: string[][]) => {
    const affine = field.slice(0, -1); // drop z
    const out: number[] = [];
    for (const pair of affine) {
      out.push(...processG2Pair(pair));
    }
    return out;
  };
  const beta = g2(vk.vk_beta_2);
  const gamma = g2(vk.vk_gamma_2);
  const delta = g2(vk.vk_delta_2);

  const ics: number[][] = vk.IC.map((pt: string[]) => [
    ...bigintToBe32(pt[0]),
    ...bigintToBe32(pt[1]),
  ]);
  const nr = ics.length - 1;

  const icBlock = ics
    .map((ic) => `\t\t[${bytesLit(ic)}],`)
    .join("\n");

  const rust = `//! Auto-generated from snarkjs verification_key.json — do not edit by hand.
//! Regenerated by: packages/zk-circuits/scripts/export_vk_rust.ts
use groth16_solana::groth16::Groth16Verifyingkey;

#[rustfmt::skip]
pub const VERIFYING_KEY: Groth16Verifyingkey<'static> = Groth16Verifyingkey {
\tnr_pubinputs: ${nr},
\tvk_alpha_g1: [${bytesLit(alpha)}],
\tvk_beta_g2: [${bytesLit(beta)}],
\tvk_gamme_g2: [${bytesLit(gamma)}],
\tvk_delta_g2: [${bytesLit(delta)}],
\tvk_ic: &[
${icBlock}
\t],
};
`;

  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, rust);
  console.log(`Wrote ${dest} (nr_pubinputs=${nr})`);
}

main();
